
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-identityconfig-identitatem-io-v1alpha1-authrealm
  failurePolicy: Fail
  name: vauthrealm.kb.io
  rules:
  - apiGroups:
    - identityconfig.identitatem.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - authrealms
  sideEffects: None
